### ISSUE TITLE
Getting error collection is not configured

### ISSUE THREAD

**Issue by ajainvivek** [tomdale/glimmer-website#35]
After following the steps from glimmerjs.com

I get error while serving ember app

`Error: The collection 'components' is not configured to contain a collection`

**Comment by locks** [comment]
@ajainvivek hi, can you tell us what the name of your application is? I've seen this error happen when it doesn't include a dash, like `hello-glimmer`.

**Comment by ajainvivek** [comment]
@locks you were right. I am not sure why the app name has to be dasherized.

Issue fixed.

**Comment by locks** [comment]
@ajainvivek it's due to the Custom Element specification. If your `<hello-glimmer />` component has a dash in the name, it avoids name collisions with existing and future  elements that might be introduced to HTML, like `<picture>` was!

**Comment by locks** [comment]
We will improve the project generation to give users a clear error so this doesn't happen, thanks for the report.
