### ISSUE TITLE
[suggestion] components TS source and HB template filenames

### ISSUE THREAD

**Issue by loicraux** [tomdale/glimmer-website#47]
Do we have to name all components TS files `component.ts` and all components HB template files `template.hbs` ?
This is not practical when searching for the source file of a given component in IDEs... It would be more practical if the files were named like this : `MyComponent.ts` and `MyComponent.hbs`, under a `MyComponent` folder.
Otherwise with the current recommandation(?) you end up with N files all named `component.ts/template.hbs`....

**Comment by acorncom** [comment]
@loicraux yes, naming needs to go as indicated in the docs. Naming approaches were discussed and debated fairly thoroughly as part of the original file layout discussion here: https://github.com/emberjs/rfcs/pull/143

It is possible to override and alter the resolver to get custom behavior, but that might lead to other difficulties down the road, so I generally don't recommend it ... :grinning:

Will close this issue for now
